[package]
name = "siostail"
version = "0.1.0"
authors = ["Pablo Couto <pablo@uncharted.space>"]

[dependencies]
crest = { git = "file:///home/pablo/code/public/crest", branch = "next" }
futures = "0.1"
hyper = "0.11"
serde_json = "1.0"